workflows:
    react-native-android:
      name: Android Build workflow
      max_build_duration: 120
      instance_type: mac_mini_m1
      environment:
        android_signing:
          - main-skirmish
        vars:
          PACKAGE_NAME: "io.skirmish.app"
      scripts:
        - name: Install npm dependencies
          script: | 
            npm install
        - name: Set Android SDK location
          script: | 
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
        - name: Build Android release
          script: | 
            cd android
            ./gradlew bundleRelease

      artifacts:
        - android/app/build/outputs/**/*.aab

      publishing:
        email:
          recipients:
            - development@mowoe.com
          notify:
            success: true 
            failure: true