/* Skirmish constants */
const SKConst = {
  ACTION_KEEP_ALIVE: 0,
  ACTION_TIMESYNC: 1,
  ACTION_JOIN_GAME: 2,
  ACTION_JOINED_GAME: 3,
  ACTION_LEAVE_GAME: 4,
  ACTION_GAME_CLOSED: 5,
  ACTION_GOT_HIT: 6,
  ACTION_SEND_SHOT: 7,
  ACTION_HIT_VALID: 8,
  ACTION_SHOT_HIT: 9,
  ACTION_ADD_AMMO: 10,
  ACTION_JOINED_SERVER: 11,
  ACTION_FULL_DATA_UPDATE: 12,
  ACTION_SERVER_JOIN_DENIED: 13,
  ACTION_INVALID_GAME: 14,
  ACTION_POWER_OFF: 15,
  ACTION_HW_STATUS: 16,
  ACTION_HP_INIT: 17,
  ACITON_HP_GOT_HIT: 18,
  ACTION_HP_HIT_VALID: 19,

  HITPOINT_ID_PHASER: 0,
  HITPOINT_ID_CHEST: 1,
  HITPOINT_ID_BACK: 2,
  HITPOINT_ID_SHOULDER_LEFT: 3,
  HITPOINT_ID_SHOULDER_RIGHT: 4,
  HITPOINT_ID_HEAD: 5,
  HITPOINT_ID_HITPOINT: 6,
  HITPOINT_ID_UNDEFINED: 7,
};

export default SKConst;
